### ISSUE TITLE
import wx.combo

### ISSUE THREAD

**Issue by uilker** [anl-polaris/polaris#3]
Hello, 
I get an error like; 
import wx.combo
ImportError: No module named combo

I could not find the sufficient help online as well. Could you please help? Thanks.

**Comment by wissamkontar** [comment]
I had this problem also, If i remember correctly it was due to incorrect installation of a python package (I think shapely package). Try removing uninstalling and reinstalling properly the python packages. 

I am also, struggling to get everything working for Polaris, if its going well for you, maybe we can share knowledge.

**Comment by uilker** [comment]
Thanks a lot. It was due to multiple wx packages. I could solve the issue. But i am also struggling to make Polaris work. i would love to share knowledge as well.

**Comment by wissamkontar** [comment]
could you please provide me with your email so we can communicate? 
this is mine: kontar@wisc.edu

**Comment by wissamkontar** [comment]
@uilker could you please provide me with your email so we can communicate? 
This is mine: kontar@wisc.edu
